;;; ejira-core.el --- Interal functions of ejira  -*- lexical-binding: t -*-

;; Copyright (C) 2017 - 2019 Henrik Nyman

;; Author: Henrik Nyman
;; URL: https://github.com/nyyManni/ejira
;; Keywords: calendar, data, org, jira
;; Package-Requires: ((emacs "26.1"))
;; Package-Version: 1.0

;; This file is NOT part of GNU Emacs.

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs. If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; Low-level functions of Ejira package

;;; Code:

(require 'cl-lib)
(require 'org)
(require 'f)
(require 'dash)
(require 'org-id)
(require 'org-capture)

(require 's)
(require 'jiralib2)

(require 'ejira-parser)



(defgroup ejira nil
  "JIRA synchronization for Emacs."
  :group 'applications
  :prefix "ejira-")

(defvar ejira-sprint-field nil
  "Name of the sprint field as a quoted Lisp symbol.")
(defvar ejira-epic-field nil
  "Name of the issue epic field as a quoted Lisp symbol.")
(defvar ejira-epic-summary-field nil
  "Name of the epic summary field as a quoted Lisp symbol.")
(defvar ejira-epic-type-name "Epic"
  "Name of the issue type equivalent to an epic.")
(defvar ejira-story-type-name "Story"
  "Name of the issue type equivalent to a user story.")
(defvar ejira-subtask-type-name "Sub-task"
  "Name of the issue type equivalent to a subtask.")

(defcustom ejira-epic-child-type-name "Task"
  "Jira issue type to create when a TODO heading is added directly under an Epic.
Defaults to \"Task\"; set to \"Story\" if your team prefers stories under epics."
  :group 'ejira
  :type 'string)

(defcustom ejira-epic-parent-issuetypes '("Initiative")
  "Jira issue types under which new TODO headings create Epics rather than subtasks.
Defaults to (\"Initiative\").  Add other top-level planning types (e.g. \"Goal\")
if your project hierarchy uses them as Epic parents."
  :group 'ejira
  :type '(repeat string))

(defvar ejira-comments-heading-name "Comments"
  "Subheading ejira uses for the comments list.")
(defvar ejira-description-heading-name "Description"
  "Subheading ejira uses for the description of the item.")

(defcustom ejira-projects nil
  "Projects to synchronize."
  :group 'ejira
  :type '(repeat string))

(defcustom ejira-priorities-alist nil
  "Deprecated compatibility variable; Jira priorities are loaded per issue.
The priority scheme returned by Jira's issue edit metadata is authoritative.
The variable is retained so older configurations can be loaded, but it is no
longer consulted when priorities are pulled or pushed."
  :group 'ejira
  :tag "JIRA priority map"
  :type '(alist :key-type (string :tag "JIRA Priority")
                :value-type (character :tag "org-priority")))

(defcustom ejira-priority-policies nil
  "Per-project overrides for Jira priority display and selection.
Each entry is (PROJECT :ranks RANKS :fallback-rank RANK :selectable IDS
:default ID).  RANKS maps exact Jira priority IDs to one-based Org ranks.
IDs in :selectable are offered by `ejira-set-priority'; omitted Jira IDs use
:fallback-rank when present."
  :group 'ejira
  :type 'sexp)

(defcustom ejira-todo-states-alist '(("To Do"       . 1)
                                     ("In Progress" . 2)
                                     ("Done"        . 3))
  "Association list to convert from JIRA todo states to `org-mode' todo states.
The org-state is defined as a number, which is a 1-based index of an element in
`org-todo-keywords'.
The default value is applicable for:
 (setq org-todo-keywords '((sequence \"TODO\" \"IN PROGRESS\" \"|\" \"DONE\")))"
  :group 'ejira
  :tag "JIRA state map"
  :type '(alist :key-type (string :tag "JIRA State")
                :value-type (number :tag "org-todo")))

(defcustom ejira-todo-state-fn
  (lambda (status _resolution)
    (alist-get status ejira-todo-states-alist 1 nil #'equal))
  "Function to map a Jira STATUS and RESOLUTION to an org-mode todo index.
The index is 1-based into `org-todo-keywords-1'. Override to implement
resolution-aware mappings (e.g. Closed+Fixed→DONE vs Closed+Won't Fix→CANCELED)."
  :group 'ejira
  :type 'function)

(defcustom ejira-org-directory "~/org"
  "Directory to use for storing the org-files generated by ejira."
  :group 'ejira
  :type 'string)

(defvar ejira-assigned-tagname "ejira_assigned"
  "Tagname used for issues that are assigned to me.
Set to nil to disable assigned-tag management entirely.")

(defvar ejira-sprint-tagname-prefix "ejira_sprint@"
  "Tagname used prefix for the sprint tag.")

(cl-defstruct ejira-task
  (key nil :read-only t)
  type
  (reporter nil :read-only t)
  assignee
  deadline
  status
  resolution
  created
  updated
  epic
  project
  priority
  priority-id
  sprint
  estimate
  remaining-estimate
  summary
  parent
  description
  comments)

(defconst ejira-priority-id-property "JiraPriorityId"
  "Org property storing the exact Jira priority ID for a heading.")

(defconst ejira-priority-name-property "JiraPriorityName"
  "Org property storing the last-seen Jira priority name for a heading.")

(defconst ejira-priority-rank-property "JiraPriorityRank"
  "Org property storing the policy-derived display rank for a heading.")

(defvar ejira--priority-scheme-cache (make-hash-table :test #'equal)
  "Cached ordered Jira priority schemes keyed by session, URL, and issue key.")

(cl-defstruct ejira-comment
  id
  author
  created
  updated
  body)

(cl-defstruct ejira-sprint
  (id nil :read-only t)
  name
  state
  start-date
  end-date
  complete-date)

(cl-defstruct ejira-project
  (key nil :read-only t)
  name
  description)

(defun ejira--parse-sprint (s)
  "Parse a sprint object S. Return it as jira-sprint structure."
  (if (stringp s)

      ;; Some JIRA instances do not give the parsed form of a Sprint description
      ;;  We need to manually parse the ugly format.
      (let ((args
             (mapcar
              (lambda (p)
                (apply 'cons (split-string p "=")))

              ;; Throw away items not containing =-character. They probably are
              ;; there due to an extra , in some of the fields. This results in
              ;; field values being truncated on first comma. I blame JIRA for
              ;; not escaping the commas properly.
              (cl-remove-if-not
               (-partial #'s-contains-p "=")
               (split-string
                (replace-regexp-in-string "^.*@[0-9a-f]*\\[\\(.*\\)\\]$" "\\1" s) ",")))))

        (make-ejira-sprint
         :id (cdr (assoc "id" args))
         :name (cdr (assoc "name" args))
         :state (cdr (assoc "state" args))
         :start-date (condition-case  nil
                         (ejira--date-to-time (cdr (assoc "startDate" args)))
                       (error nil))
         :end-date (condition-case nil
                       (ejira--date-to-time (cdr (assoc "endDate" args)))
                     (error nil))
         :complete-date (condition-case nil
                            (ejira--date-to-time (cdr (assoc "completeDate" args)))
                          (error nil))))
    (make-ejira-sprint
     :id (cdr (assoc 'id s))
     :name (cdr (assoc 'name s))
     :state (cdr (assoc 'state s))
     :start-date (condition-case  nil
                     (ejira--date-to-time (cdr (assoc 'startDate s)))
                   (error nil))
     :end-date (condition-case nil
                   (ejira--date-to-time (cdr (assoc 'endDate s)))
                 (error nil))
     :complete-date (condition-case nil
                        (ejira--date-to-time (cdr (assoc 'completeDate s)))
                      (error nil)))))

(defun ejira--parse-project (project)
  "Parse a project structure from REST object PROJECT."
  (make-ejira-project
   :key (ejira--alist-get project 'key)
   :name (ejira--alist-get project 'name)
   :description (ejira--alist-get project 'description)))

(defun ejira--parse-comment (comment)
  "Parse a comment structure from REST object COMMENT."
  (make-ejira-comment
   :id (ejira--alist-get comment 'id)
   :author (ejira--alist-get comment 'author 'displayName)
   :created (ejira--date-to-time (ejira--alist-get comment 'fields 'created))
   :updated (ejira--date-to-time (ejira--alist-get comment 'fields 'updated))
   :body (ejira--alist-get comment 'body)))

(defun ejira--parse-item (item)
  "Parse an issue or epic structure from REST object ITEM."
  (let ((type (ejira--alist-get item 'fields 'issuetype 'name)))
    (make-ejira-task
     :key (ejira--alist-get item 'key)
     :type type
     :status (ejira--alist-get item 'fields 'status 'name)
     :resolution (ejira--alist-get item 'fields 'resolution 'name)
     :created (ejira--date-to-time (ejira--alist-get item 'fields 'created))
     :updated (ejira--date-to-time (ejira--alist-get item 'fields 'updated))
     :reporter (ejira--alist-get item 'fields 'reporter 'displayName)
     :assignee (ejira--alist-get item 'fields 'assignee 'displayName)
     :deadline (ejira--alist-get item 'fields 'duedate)
     :epic (unless (equal type ejira-epic-type-name)
             (ejira--alist-get item 'fields ejira-epic-field))
     :project (ejira--alist-get item 'fields 'project 'key)
     :estimate (ejira--alist-get item 'fields 'timetracking
                                 'originalEstimateSeconds)
     :remaining-estimate (ejira--alist-get item 'fields 'timetracking
                                           'remainingEstimateSeconds)
     :sprint (ejira-get-sprint-name (ejira--alist-get item 'fields
                                                      ejira-sprint-field))
     :parent (when (equal type ejira-subtask-type-name)
               (ejira--alist-get item 'fields 'parent 'key))
     :priority (ejira--alist-get item 'fields 'priority 'name)
     :priority-id (when-let ((id (ejira--alist-get item 'fields 'priority 'id)))
                    (format "%s" id))
     :summary (ejira--parse-body (ejira--alist-get item 'fields 'summary))
     :description (ejira--alist-get item 'fields 'description)
     :comments (mapcar #'ejira--parse-comment
                       (ejira--alist-get item 'fields 'comment 'comments)))))

(defun ejira--priority-id-string (id)
  "Return ID as a string, or nil when ID is absent."
  (when id (format "%s" id)))

(defun ejira--parse-priority-scheme (editmeta)
  "Return ordered priority records from Jira EDITMETA.
Each record is a plist containing :id and :name.  The order is the order
returned by Jira's `allowedValues', which is the issue's applicable scheme."
  (let ((allowed-values (ejira--alist-get editmeta 'fields 'priority
                                          'allowedValues)))
    (when (vectorp allowed-values)
      (setq allowed-values (append allowed-values nil)))
    (cl-loop for value in allowed-values
             for id = (ejira--priority-id-string
                       (ejira--alist-get value 'id))
             for name = (ejira--alist-get value 'name)
             when (and id name)
             collect (list :id id :name name))))

(defun ejira--priority-scheme-cache-key (issue-key)
  "Return the cache key for ISSUE-KEY in the active Jira session."
  (list jiralib2-url jiralib2--session issue-key))

(defun ejira--clear-priority-scheme-cache (&rest _args)
  "Clear cached Jira priority schemes."
  (when (hash-table-p ejira--priority-scheme-cache)
    (clrhash ejira--priority-scheme-cache)))

(advice-add 'jiralib2-session-logout :after #'ejira--clear-priority-scheme-cache)

(defun ejira--get-priority-scheme (issue-key &optional refresh)
  "Return the ordered priority scheme applicable to ISSUE-KEY.
The result is read from Jira's issue edit metadata and cached for the active
session.  A nil result means the priority field is not editable or Jira did
not provide allowed values."
  (unless (hash-table-p ejira--priority-scheme-cache)
    (setq ejira--priority-scheme-cache (make-hash-table :test #'equal)))
  (let ((cache-key (ejira--priority-scheme-cache-key issue-key)))
    (or (and (not refresh) (gethash cache-key ejira--priority-scheme-cache))
        (condition-case err
            (let ((scheme (ejira--parse-priority-scheme
                           (jiralib2-session-call
                            (format "/rest/api/2/issue/%s/editmeta" issue-key)))))
              (when scheme
                (puthash cache-key scheme ejira--priority-scheme-cache))
              scheme)
          (error
           (display-warning
            'ejira
            (format "Could not retrieve priority scheme for %s: %s"
                    issue-key (error-message-string err))
            :warning)
           nil)))))

(defun ejira--priority-entry-by-id (scheme priority-id)
  "Return the entry in SCHEME whose Jira ID is PRIORITY-ID."
  (when priority-id
    (cl-find (ejira--priority-id-string priority-id) scheme
             :key (lambda (entry) (plist-get entry :id))
             :test #'equal)))

(defun ejira--priority-entry-by-rank (scheme rank)
  "Return the RANK-th entry in ordered SCHEME, or nil."
  (when (and (integerp rank) (> rank 0))
    (nth (1- rank) scheme)))

(defun ejira--priority-policy (project)
  "Return the configured priority policy for PROJECT, or nil."
  (cdr (assoc project ejira-priority-policies)))

(defun ejira--priority-policy-rank (project priority-id)
  "Return PROJECT's configured rank for PRIORITY-ID, or nil."
  (when-let ((policy (ejira--priority-policy project)))
    (or (cdr (assoc (ejira--priority-id-string priority-id)
                    (plist-get policy :ranks)))
        (plist-get policy :fallback-rank))))

(defun ejira--selectable-priority-scheme (project scheme)
  "Return the priorities from SCHEME selectable in PROJECT."
  (let* ((policy (ejira--priority-policy project))
         (selectable (plist-get policy :selectable)))
    (if (and policy selectable)
        (cl-remove-if-not
         (lambda (entry) (member (plist-get entry :id) selectable))
         scheme)
      scheme)))

(defun ejira--priority-rank (scheme priority-id &optional project)
  "Return the one-based rank of PRIORITY-ID in SCHEME.
Use PROJECT's configured policy when one exists."
  (or (ejira--priority-policy-rank project priority-id)
      (when-let ((position
                  (cl-position (ejira--priority-id-string priority-id) scheme
                               :key (lambda (entry) (plist-get entry :id))
                               :test #'equal)))
        (1+ position))))

(defun ejira--priority-entry-for-rank (project scheme rank)
  "Return the selectable SCHEME entry corresponding to PROJECT RANK."
  (cl-find rank (ejira--selectable-priority-scheme project scheme)
           :key (lambda (entry)
                  (ejira--priority-rank scheme (plist-get entry :id) project))))

(defun ejira--default-priority-id (project &optional reference-key)
  "Return the default priority ID for new issues in PROJECT.
REFERENCE-KEY supplies an existing issue whose edit metadata can provide the
scheme when PROJECT has no explicit policy."
  (let* ((policy (ejira--priority-policy project))
         (configured (plist-get policy :default))
         (selectable (plist-get policy :selectable)))
    (or configured
        (car selectable)
        (when reference-key
          (car (mapcar (lambda (entry) (plist-get entry :id))
                       (ejira--get-priority-scheme reference-key)))))))

(defun ejira--org-priority-numeric-p ()
  "Return non-nil when Org's configured priority range is numeric."
  (< org-priority-lowest 65))

(defun ejira--org-priority-for-rank (rank)
  "Return the Org priority value corresponding to Jira scheme RANK."
  (if (ejira--org-priority-numeric-p)
      rank
    (+ org-priority-highest (1- rank))))

(defun ejira--org-priority-rank (priority)
  "Return the Jira-style rank represented by Org PRIORITY.
PRIORITY may be the string captured from an Org priority cookie."
  (when priority
    (let ((value (org-priority-to-value (format "%s" priority))))
      (if (ejira--org-priority-numeric-p)
          value
        (1+ (- (upcase value) (upcase org-priority-highest)))))))

(defun ejira--ensure-org-priority-range (rank)
  "Extend Org's configured priority range to include Jira scheme RANK."
  (let ((lowest (ejira--org-priority-for-rank rank)))
    (when (> lowest org-priority-lowest)
      (setq org-priority-lowest lowest))
    ;; Older Org versions and orgist use the unprefixed aliases.
    (when (and (boundp 'org-lowest-priority)
               (> lowest org-lowest-priority))
      (setq org-lowest-priority lowest))))

(defun ejira--set-task-priority (marker priority-id priority-name scheme
                                        &optional project)
  "Set MARKER's Org priority and Jira metadata from SCHEME.
PRIORITY-ID and PRIORITY-NAME are authoritative Jira values.  If the ID is
not present in SCHEME, preserve the existing Org cookie but still record the
Jira identity so a later refresh can retry the mapping safely."
  (org-with-point-at marker
    (if priority-id
        (progn
          (let ((rank (ejira--priority-rank scheme priority-id project)))
            (if rank
                (progn
                  (ejira--ensure-org-priority-range rank)
                  (org-priority (ejira--org-priority-for-rank rank))
                  (org-set-property ejira-priority-rank-property
                                    (number-to-string rank)))
              (org-delete-property ejira-priority-rank-property)))
          (org-set-property ejira-priority-id-property
                            (ejira--priority-id-string priority-id))
          (if priority-name
              (org-set-property ejira-priority-name-property priority-name)
            (org-delete-property ejira-priority-name-property)))
      (when (save-excursion
              (org-back-to-heading t)
              (looking-at org-priority-regexp))
        (org-priority 'remove))
      (org-delete-property ejira-priority-id-property)
      (org-delete-property ejira-priority-name-property)
      (org-delete-property ejira-priority-rank-property))))

(defun ejira--local-priority-entry (marker scheme &optional project)
  "Return the Jira priority entry represented by MARKER, or nil.
Headings without `JiraPriorityId' are legacy data and deliberately do not
produce an outbound priority.  Once metadata exists, a direct Org cookie edit
is resolved by the current scheme rank; the stored ID is used when the rank
has not changed so duplicate or renamed Jira names remain safe."
  (when scheme
    (org-with-point-at marker
      (let* ((stored-id (org-entry-get (point-marker)
                                       ejira-priority-id-property))
             (stored-entry (ejira--priority-entry-by-id scheme stored-id))
             (priority (save-excursion
                         (org-back-to-heading t)
                         (when (looking-at org-priority-regexp)
                           (match-string 2))))
             (rank (ejira--org-priority-rank priority))
             (stored-rank (ejira--priority-rank
                           scheme (plist-get stored-entry :id) project)))
        (when (and stored-entry rank)
          (if (= rank stored-rank)
              stored-entry
            (ejira--priority-entry-for-rank project scheme rank)))))))

(defun ejira--project-file-name (key)
  "Get file path for the project KEY."
  (if (s-ends-with? "/" ejira-org-directory)
      (concat ejira-org-directory key ".org")
    (concat ejira-org-directory "/" key ".org")))


(defun ejira--update-project (key)
  "Pull the project KEY from the server and update it's org state."
  (save-window-excursion
    (save-current-buffer
      (let* ((existing-heading (ejira--find-heading key))
             (project (ejira--parse-project (jiralib2-get-project key)))
             (project-file-name (ejira--project-file-name key))
             (exists-p (f-exists-p project-file-name)))

        ;; We need to write empty file so that `org-id' will start tracking it.
        (unless exists-p
          (write-region "" nil project-file-name)
          (add-to-list 'org-agenda-files project-file-name))
        (let ((project-buffer (or (find-buffer-visiting project-file-name)
                                  (find-file-noselect project-file-name))))

          (unless existing-heading
            (ejira--new-heading project-buffer nil key))

          (ejira--set-summary key (ejira-project-name project))
          (ejira--set-property key "TYPE" "ejira-project"))))))

(defmacro ejira--with-bind-struct (type instance &rest body)
  "Bind slots of INSTANCE to locals while evaluating BODY.
The slots are parsed from struct TYPE."
  (let ((sym (gensym)))
    `(let* ,(cons
             `(,sym ,instance)
             (mapcar
              (lambda (s) `(,s (cl-struct-slot-value ',type ',s ,sym)))
              (mapcar #'car (cdr (cl-struct-slot-info type)))))
       ,@body)))
(function-put #'ejira--with-bind-struct 'lisp-indent-function 'defun)

(defvar ejira--syncing nil
  "Non-nil during `ejira-update-project' to suppress per-op outline expand.")

(defvar ejira--heading-cache nil
  "Hash table ID->marker, valid for the duration of one `ejira-update-project'.
Avoids repeated linear file scans for the same heading.  Markers auto-update
on buffer edits, so they stay valid through property changes.  Entries for
refiled headings are evicted after the refile.")

(defvar ejira--pre-scanning nil
  "Bound to t when the buffer is pre-expanded for a push scan+build pass.
Like `ejira--syncing', causes `ejira--with-expand-all' to skip the per-call
`outline-show-all' since the caller already widened and showed everything.")

(defmacro ejira--with-expand-all (&rest body)
  "Evalate BODY while all outline contents are visible.
During sync (`ejira--syncing' t) or a push scan (`ejira--pre-scanning' t)
the buffer is pre-expanded once and this macro becomes a bare progn to
avoid repeated save/restore overhead."
  `(if (or ejira--syncing ejira--pre-scanning)
       (progn ,@body)
     (org-save-outline-visibility t
       (outline-show-all)
       ,@body)))
(function-put #'ejira--with-expand-all 'lisp-indent-function 'defun)

(defmacro ejira--with-point-on (id &rest body)
  "Execute BODY with point on the item ID header."
  `(org-with-point-at (or (ejira--find-heading ,id)
                          (error "Item %s not found" ,id))
     ,@body))
(function-put #'ejira--with-point-on 'lisp-indent-function 'defun)

(defun ejira--update-task-light (issue-key status assignee &optional resolution)
  "Update only the STATUS and ASSIGNEE of issue ISSUE-KEY.
If the issue heading does not exist, fallback to full update."
  (if (not (ejira--find-heading issue-key))
      (ejira--update-task issue-key)

    (ejira--with-point-on issue-key
      (unless (equal (org-entry-get (point-marker) "Status") status)
        (org-set-property "Status" status))
      (let ((target-assignee (or assignee "")))
        (unless (equal (org-entry-get (point-marker) "Assignee") target-assignee)
          (org-set-property "Assignee" target-assignee)))
      (when ejira-assigned-tagname
        (let ((has-tag (member ejira-assigned-tagname (org-get-tags))))
          (if (equal assignee (ejira--my-fullname))
              (unless has-tag (org-toggle-tag ejira-assigned-tagname 'on))
            (when has-tag (org-toggle-tag ejira-assigned-tagname 'off))))))
    (ejira--set-todo-state issue-key
                           (funcall ejira-todo-state-fn status resolution))
    ;; Refresh push baseline so sync-induced state/assignee changes are not
    ;; mistaken for local edits on the next save.
    (ejira--with-point-on issue-key
      (ejira--update-push-baseline))))

(defun ejira--update-task (issue-key)
  "Pull the task ISSUE-KEY from the server and update it's org state."
  (ejira--with-bind-struct ejira-task (if (ejira-task-p issue-key) issue-key
                                        (ejira--parse-item
                                         (jiralib2-get-issue issue-key)))

    (let ((org-type (cond ((equal type ejira-epic-type-name) 'ejira-epic)
                          ((equal type ejira-story-type-name) 'ejira-story)
                          ((equal type ejira-subtask-type-name) 'ejira-subtask)
                          (t 'ejira-issue))))

      ;; Ensure that the project file is there to begin with.
      (unless (ejira--find-heading project) (ejira--update-project project))

      ;; Subtasks parent needs to be updated first so we can refile
      (when (and parent (not (ejira--find-heading parent))) (ejira--update-task parent))

      ;; Epic needs to be updated first, so that we can refile
      (when (and epic (not (ejira--find-heading epic))) (ejira--update-task epic))

      ;; Find or create the issue heading.  Bind the marker so the skip check
      ;; and any other callers reuse the same cache hit rather than calling
      ;; ejira--find-heading again.
      (unless (ejira--find-heading key)
        (when (fboundp 'helm-ejira-invalidate-cache) (helm-ejira-invalidate-cache))
        (ejira--new-heading (marker-buffer (ejira--find-heading project))
                            (or parent project)
                            key))
      (let* ((key-m (ejira--find-heading key))
             (modified-p
              (not (equal (org-entry-get key-m "Modified")
                          (format-time-string "%Y-%m-%d %H:%M:%S"
                                              updated "UTC"))))
             ;; A legacy heading can already contain a real local edit.  Do
             ;; not reinterpret its old Org cookie as an outbound Jira
             ;; priority while migrating it.
             (local-dirty-p
              (org-with-point-at key-m (ejira--locally-modified-p)))
             (stored-priority-id
              (org-entry-get key-m ejira-priority-id-property))
             (stored-priority-name
              (org-entry-get key-m ejira-priority-name-property))
             (stored-priority-rank
              (org-entry-get key-m ejira-priority-rank-property))
             (priority-scheme
              (when priority-id (ejira--get-priority-scheme key)))
             (remote-priority-rank
              (when priority-id
                (ejira--priority-rank priority-scheme priority-id project)))
             (priority-needs-sync
              (or modified-p
                  (not (equal stored-priority-id priority-id))
                  (not (equal stored-priority-name priority))
                  (not (equal stored-priority-rank
                              (and remote-priority-rank
                                   (number-to-string remote-priority-rank))))))
             (priority-migration-skipped-p
              (and local-dirty-p
                   (not stored-priority-id)
                   priority-needs-sync))
             (priority-applied-p nil))

        ;; Priority metadata is handled separately so an unchanged heading can
        ;; still be migrated from the old global name map.
        (when (and priority-needs-sync (not priority-migration-skipped-p))
          (ejira--set-task-priority key-m priority-id priority priority-scheme project)
          (setq priority-applied-p t))

        ;; Skip expensive field/comment updates when Jira reports no changes.
        ;; Modified stores the last-seen Jira updated timestamp; equality means
        ;; nothing else on the server changed since the last sync.
        (when modified-p
          (ejira--set-todo-state key (funcall ejira-todo-state-fn status resolution))

          (ejira--set-property key "TYPE" (symbol-name org-type))
          (ejira--set-summary key summary)

          ;; Set the sprint tag
          (ejira--with-point-on key
            (dolist (tag (org-get-tags))
              (when (s-starts-with-p ejira-sprint-tagname-prefix tag)
                (org-toggle-tag tag 'off)))

            (when sprint (org-toggle-tag sprint 'on))

            ;; Update deadline (4 is the prefix argument to remove deadline)
            (if deadline (org-deadline nil deadline) (org-deadline '(4)))

            (org-set-property "Status" status)
            (when reporter
              (org-set-property "Reporter" reporter))
            (org-set-property "Assignee" (or assignee ""))
            (when ejira-assigned-tagname
              (if (equal assignee (ejira--my-fullname))
                  (org-toggle-tag ejira-assigned-tagname 'on)
                (org-toggle-tag ejira-assigned-tagname 'off)))

            (org-set-property "Issuetype" type)
            (org-set-property "Created" (format-time-string "%Y-%m-%d %H:%M:%S"
                                                            created "UTC"))
            (org-set-property "Modified" (format-time-string "%Y-%m-%d %H:%M:%S"
                                                             updated "UTC"))
            (when-let ((minutes (and estimate (/ estimate 60))))
              (org-set-property "Effort" (format "%02d:%02d" (/ minutes 60) (% minutes 60))))
            (when-let ((minutes (and remaining-estimate (/ remaining-estimate 60))))
              (org-set-property "Left" (format "%02d:%02d" (/ minutes 60) (% minutes 60)))))

          (ejira--get-subheading (ejira--find-heading key) ejira-description-heading-name)
          (ejira--get-subheading (ejira--find-heading key) ejira-comments-heading-name)
          (ejira--set-heading-body-jira-markup
           (ejira--find-task-subheading key ejira-description-heading-name)
           description)

          ;; Update existing, and insert missing comments
          (mapc (-partial #'ejira--update-comment key) comments)

          ;; Delete removed comments
          (ejira--kill-deleted-comments key (mapcar 'ejira-comment-id comments))

          ;; Ensure comments are ordered by creation
          (ejira--sort-comments key)

          ;; Refile to enforce the Jira hierarchy.  For parent/epic always enforce
          ;; so subtasks and stories stay nested correctly.  For the project-level
          ;; fallback, skip if the heading has been manually moved outside
          ;; ejira-org-directory — use file-truename on both sides to handle symlinks.
          (let* ((target (cond (parent) (epic) (t project)))
                 (heading-file (buffer-file-name
                                (marker-buffer (ejira--find-heading key))))
                 (in-ejira-dir (string-prefix-p
                                (file-truename (expand-file-name ejira-org-directory))
                                (file-truename heading-file))))
            (when (or parent epic in-ejira-dir)
              (ejira--refile key target)))
          (message "Updated %s: %s" key summary)
          ;; Record the push baseline from the content we just wrote so later
          ;; local edits are detectable.  Kept inside the guard: an unchanged
          ;; item keeps its still-valid baseline and pays nothing — recomputing
          ;; it for every item turned a no-op sync into O(items) body scans.
          (ejira--with-point-on key (ejira--update-push-baseline)))

        ;; For an unchanged, clean legacy heading, the priority migration is
        ;; the only content change and must establish a new clean baseline.
        (when (and priority-applied-p (not modified-p) (not local-dirty-p))
          (ejira--with-point-on key (ejira--update-push-baseline)))))))

(defun ejira--update-comment (key comment)
  "Update comment list of item KEY with data from COMMENT."
  (org-with-point-at (ejira--get-comment-heading key (ejira-comment-id comment))
    (ejira--with-expand-all
      (org-set-property "Author" (ejira-comment-author comment))
      (let ((created (ejira-comment-created comment))
            (updated (ejira-comment-updated comment)))

        (org-set-property "Created" (format-time-string "%Y-%m-%d %H:%M:%S"
                                                        created "UTC"))
        (when (not (equal created updated))
          (org-set-property "Modified" (format-time-string "%Y-%m-%d %H:%M:%S"
                                                           updated "UTC"))))
      (ejira--set-heading-summary
       (point-marker)
       (format "[%s] %s"
               (format-time-string "%Y-%m-%d %a %H:%M"
                                   (ejira-comment-created comment) "UTC")
               (ejira-comment-author comment)))
      (ejira--set-heading-body-jira-markup
       (point-marker)
       (ejira-comment-body comment))
      (ejira--update-push-baseline))))

(defun ejira--get-comment-heading (key id)
  "Get marker to comment ID of item KEY. Create heading if it does not exits."
  (org-with-point-at (ejira--get-subheading (ejira--find-heading key)
                                            ejira-comments-heading-name)
    (or (ejira--find-child-heading-property "CommId" id)
        (org-with-wide-buffer
         (ejira--with-expand-all
           (org-insert-heading-respect-content t)
           (insert "<new comment>")
           (org-demote-subtree)
           (beginning-of-line)
           (org-set-property "CommId" id)
           (org-set-property "TYPE" "ejira-comment")
           (point-marker))))))

(defun ejira--sort-comments (key)
  "Sort comments of item KEY by creation time.
Skipped unless there are at least two comments: `org-sort-entries' on an
empty or single-entry subtree is pointless and, with a live org-element
cache in a displayed buffer, can wedge into an uninterruptible loop."
  (org-with-point-at (ejira--get-subheading (ejira--find-heading key)
                                            ejira-comments-heading-name)
    (when (> (length (org-map-entries t "TYPE=\"ejira-comment\"" 'tree)) 1)
      (condition-case nil
          (org-sort-entries nil ?r nil #'time-less-p "Created" nil)
        (user-error nil)))))  ;; User error thrown if no subheadings

(defun ejira--kill-deleted-comments (key ids)
  "Kill all comments of item KEY whoes ids are not found from IDS."
  (ejira--with-point-on key
    (mapc
     (lambda (m) (when m (org-with-point-at m
                           (ejira--with-expand-all
                             (org-cut-subtree)))))
     (org-with-point-at (ejira--get-subheading (ejira--find-heading key)
                                               ejira-comments-heading-name)
       (org-map-entries
        `(let ((cid (org-entry-get (point-marker) "CommId")))
           (when (and cid (not (member cid ',ids)))
             (point-marker)))
        "TYPE=\"ejira-comment\""
        'tree)))))

(defun ejira--get-comment-capture-target (key)
  "Get an `org-capture'-target for adding a comment to task KEY."
  (ejira--with-point-on key
    (let ((l `(,(ejira--strip-properties (org-get-heading t t t t)))))
      (condition-case nil
          (while t
            (outline-up-heading 1 t)
            (setq l (cons (ejira--strip-properties (org-get-heading t t t t)) l)))
        (error nil))
      `(file+olp ,(buffer-file-name) ,@l ,ejira-comments-heading-name))))

(defun ejira--capture-comment (key)
  "Capture a comment into task KEY."
  (let ((org-capture-templates
         `(("x" "Comment" entry
            ,(ejira--get-comment-capture-target key)
            "* <new comment>\n:PROPERTIES:\n:TYPE:     ejira-comment\n:END:\n%?"))))
    (org-capture nil "x")))

(defun ejira--post-capture-comment ()
  "Stage captured comment for push via ejira-confirm on next save."
  (unless org-note-abort
    (when-let ((m (save-excursion
                    (when (search-backward "<new comment>" nil t)
                      (beginning-of-line)
                      (point-marker)))))
      (when (equal (org-entry-get m "TYPE") "ejira-comment")
        ;; Initialise pushhash so the heading is baseline-clean.  The scan
        ;; detects it as a new-comment draft (TYPE=ejira-comment, no CommId).
        (org-with-point-at m (ejira--update-push-baseline))))))

(defun ejira--heading-body-level (heading)
  "Return the heading-shift level used when parsing JIRA body under HEADING."
  (+ 2 (org-with-point-at heading
         (save-match-data
           (search-forward-regexp "^\\**" (line-end-position) t)
           (length (or (match-data) ""))))))

(defun ejira--expected-org-body (heading content)
  "Return the org body that JIRA markup CONTENT would produce under HEADING.
This mirrors exactly what `ejira--set-heading-body-jira-markup' stores, so it
can be compared against the current body to detect whether a push is needed."
  (ejira--parse-body content (ejira--heading-body-level heading)))

(defun ejira--set-heading-body-jira-markup (heading content)
  "Update body of heading HEADING to parsed JIRA markup from CONTENT.
The content will be adjusted based on the heading level."
  (ejira--set-heading-body heading (ejira--expected-org-body heading content)))

(defun ejira--find-task-subheading (id heading)
  "Return marker to the subheading HEADING of task ID."
  (ejira--with-point-on id
    (ejira--find-child-heading heading)))

(defun ejira--parse-body (body &optional level)
  "Parse a JIRA BODY to insert it inside org header.
If LEVEL is given, shift all heading by it."
  (cl-flet ((r (a b c) (replace-regexp-in-string a b c)))
    (concat
     (s-trim
      (ejira-parser-jira-to-org
       (r "" ""    ; Windows line-endings
          (r " " " " ; Non-breaking space, JIRA likes these, Emacs doesn't
             (decode-coding-string (or body "") 'utf-8)))
       level))
     "")))

(defun ejira--get-project (key)
  "Get project id of item KEY."
  (ejira--with-point-on key
    (nth 1 (ejira-get-id-under-point "ejira-project"))))

(defmacro ejira--with-narrow-to-body (heading &rest body)
  "Execute BODY while the buffer is narrowed to the content under HEADING."
  `(org-with-point-at ,heading
     (ejira--with-expand-all
       (goto-char ,heading)
       (org-narrow-to-subtree)
       (end-of-line)

       ;; TODO: Subheading content might have these...
       (search-forward-regexp org-deadline-line-regexp nil t)
       (search-forward-regexp org-property-drawer-re nil t)

       ;; Clock drawer requires a hack, as the built-in regexp doesn't work
       (search-forward-regexp
        (let ((s (replace-regexp-in-string "CLOCK" "LOGBOOK" org-clock-drawer-re)))
          (substring s 0 (- (length s) 2)))
        nil t)
       (narrow-to-region
        (point)
        (point-max))
       ,@body)))
(function-put #'ejira--with-narrow-to-body 'lisp-indent-function 'defun)

(defun ejira--get-heading-body (heading)
  "Get body of HEADING."
  (ejira--with-narrow-to-body heading
    (let* ((buf (buffer-string))
           (s (if (and (> (length buf) 0)
                       (s-starts-with-p "\n" buf))
                  (substring buf 1)
                buf)))

      (set-text-properties 0 (length s) nil s)
      s)))

(defun ejira--strip-properties (s)
  "Remove text properties from string S."
  (set-text-properties 0 (length s) nil s)
  s)

(defconst ejira-pushable-types
  '("ejira-issue" "ejira-story" "ejira-subtask" "ejira-epic" "ejira-comment")
  "Heading TYPE values whose content can be pushed back to Jira.")

(defun ejira--push-normalize (s)
  "Normalize S for push fingerprinting: strip CR and trim surrounding space.
Must match the comparison normalization in `ejira-confirm--normalize' so the
hash flips only when a real (pushable) difference exists, not when refile or
org editing nudges trailing whitespace."
  (string-trim (replace-regexp-in-string "\r" "" (or s ""))))

(defun ejira--heading-pushable-content ()
  "Return the push-relevant content of the ejira heading at point, or nil.
For an issue this is its summary plus description body; for a comment, its
body.  Normalized so the fingerprint ignores cosmetic whitespace changes."
  (let ((type (org-entry-get nil "TYPE")))
    (cond
     ((equal type "ejira-comment")
      (ejira--push-normalize (ejira--get-heading-body (point-marker))))
     ((member type ejira-pushable-types)
      ;; Description is a direct child; find it point-locally to avoid org-id scans.
      (let ((desc (ejira--find-child-heading ejira-description-heading-name)))
        (concat (ejira--push-normalize
                 (ejira--strip-properties (org-get-heading t t t t)))
                "\0"
                (ejira--push-normalize
                 (if desc (ejira--get-heading-body desc) ""))
                "\0"
                (ejira--push-normalize
                 (or (org-entry-get nil "Assignee") ""))
                "\0"
                (ejira--push-normalize
                 (or (save-excursion
                       (org-back-to-heading t)
                       (when (looking-at org-priority-regexp)
                         (match-string 2)))
                     ""))
                ;; Include the exact Jira identity once a heading has been
                ;; migrated.  Omitting it for legacy headings preserves their
                ;; existing baseline until the safe migration path runs.
                (or (when-let ((priority-id
                                (org-entry-get nil ejira-priority-id-property)))
                      (concat "\0" (ejira--push-normalize priority-id)))
                    "")
                "\0"
                (ejira--push-normalize
                 (or (when-let ((d (org-get-deadline-time (point-marker))))
                       (format-time-string "%Y-%m-%d" d))
                     ""))
                "\0"
                (ejira--push-normalize
                 (or (org-get-todo-state) ""))))))))

(defun ejira--update-push-baseline ()
  "Store the :Pushhash: property fingerprinting the heading at point.
A later save whose content hashes differently is treated as a local edit."
  (when-let ((content (ejira--heading-pushable-content)))
    (org-set-property "Pushhash" (md5 content))))

(defun ejira--locally-modified-p ()
  "Return non-nil if the ejira heading at point differs from its push baseline.
Headings without a :Pushhash: baseline are treated as unmodified; the baseline
is established on the next sync or push, never during a plain save."
  (when-let ((baseline (org-entry-get nil "Pushhash"))
             (content (ejira--heading-pushable-content)))
    (not (equal baseline (md5 content)))))

(defun ejira--normalize-end-spacing ()
  "Ensure exactly one blank line after every :END: drawer closer in the current buffer."
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "^[ \t]*:END:[ \t]*\n" nil t)
      ;; Count blank lines immediately following :END:, then only modify
      ;; if spacing is wrong.  Skip the delete+insert entirely when there's
      ;; already exactly one blank line — this avoids triggering
      ;; after-change-functions (org-indent, jit-lock, goggles) for every
      ;; :END: in the buffer on a no-op sync.
      (let ((blanks 0))
        (save-excursion
          (while (and (not (eobp)) (looking-at "[ \t]*\n"))
            (cl-incf blanks)
            (forward-line 1)))
        (cond
         ((= blanks 0)
          (unless (eobp) (insert "\n")))
         ((> blanks 1)
          (while (and (not (eobp)) (looking-at "[ \t]*\n"))
            (delete-region (point) (line-beginning-position 2)))
          (unless (eobp) (insert "\n"))))))))

(defun ejira--set-heading-body (heading contents)
  "Set the contents of item HEADING to CONTENTS."
  (ejira--with-narrow-to-body heading
    (when (> (point-max) (point-min))
      (delete-region (point-min) (point-max)))
    (if (and contents (> (length contents) 0))
        ;; One blank line before and after body text.
        (insert (concat "\n\n" contents "\n"))
      ;; No body: one blank line between drawer and next heading.
      (insert "\n"))))

(defun ejira--set-todo-state (key state)
  "Set todo state of item KEY into STATE."
  (ejira--with-point-on key
    ;; state is a 1-based index into org-todo-keywords-1; resolve to string
    ;; before comparing so the guard works for both numeric and string inputs.
    (let ((target (if (numberp state) (nth (1- state) org-todo-keywords-1) state)))
      (unless (equal (org-get-todo-state) target)
        ;; Inhibit logbook and todo blockers: sync is not an interactive user
        ;; action, state history lives in Jira not in the org LOGBOOK drawer,
        ;; and dependency blockers (org-block-todo-from-children-or-siblings-or-parent,
        ;; org-edna) must not prevent reflecting Jira's authoritative status.
        (let ((org-inhibit-logging t)
              (org-blocker-hook nil))
          (org-todo state))))))

(defun ejira--is-parent-p (child parent)
  "Return t if CHILD is a subheading of PARENT."
  (ejira--with-point-on child
    (condition-case nil
        (progn
          (outline-up-heading 1 t)
          (equal parent (org-entry-get (point-marker) "ID")))
      (error nil))))


(defun ejira--new-heading (buffer parent id)
  "Create a header with ID under PARENT into BUFFER and return a marker to it.
If TITLE is given, use it as header title. If PARENT is nil assume the beginning
of the document."
  (save-window-excursion
    (with-current-buffer buffer
      (org-with-wide-buffer
       (ejira--with-expand-all
         (goto-char (point-min))

         (if parent
             ;; Jump to end of parent's subtree and insert one level deeper.
             ;; Using org-end-of-subtree avoids inserting between the parent
             ;; heading and its :PROPERTIES: drawer, which would displace the
             ;; drawer and break org-id lookup on the parent.
             (progn
               (goto-char (ejira--find-heading parent))
               (org-end-of-subtree t t)
               (org-insert-heading t)
               (org-demote))
           ;; No parent: insert after the first line (startup keyword).
           (forward-line)
           (org-insert-heading-respect-content t))
         (insert "<ejira new heading>")
         (org-set-property "ID" id)
         (org-beginning-of-line)
         (basic-save-buffer)
         (unless (hash-table-p org-id-locations)
           (setq org-id-locations (make-hash-table :test 'equal)))
         (puthash id (abbreviate-file-name (buffer-file-name buffer)) org-id-locations)
         (point-marker))))))

(defun ejira--find-heading (id)
  "Find the item ID from agenda files, or return nil."
  (when id
    (or (and ejira--heading-cache (gethash id ejira--heading-cache))
        (let ((m (org-id-find-id-in-file id (org-id-find-id-file id) t)))
          (when (and m ejira--heading-cache)
            (puthash id m ejira--heading-cache))
          m))))


(defun ejira--refile (source-id target-id)
  "Refile item SOURCE-ID to be a child of TARGET-ID."
  (unless (ejira--is-parent-p source-id target-id)
    (let ((target-m (or (ejira--find-heading target-id)
                        (error "Target %s not found" target-id))))
      (ejira--with-point-on source-id
        (let ((org-log-refile nil))
          (org-refile nil nil
                      `(nil ,(buffer-file-name (marker-buffer target-m)) nil
                            ,(marker-position target-m)))))
      ;; The heading moved; evict from cache so the next lookup re-scans.
      (when ejira--heading-cache
        (remhash source-id ejira--heading-cache)))))

(defun ejira--set-property (id property value)
  "Set PROPERTY of item ID into VALUE."
  (ejira--with-point-on id
    (org-set-property property value)))

(defun ejira--get-property (id property)
  "Get value of PROPERTY of item ID."
  (ejira--with-point-on id
    (org-entry-get (point-marker) property)))

(defun ejira--find-child-heading-predicate (predicate)
  "Get marker to child heading with PREDICATE function returning t."
  (org-with-wide-buffer
   (ejira--with-expand-all
     (when (org-goto-first-child)
       (let ((found-p nil)
             (end-p nil))
         (while (and (not found-p) (not end-p))
           (if (funcall predicate)
               (setq found-p t)
             (unless (org-goto-sibling)
               (setq end-p t))))
         (when found-p
           (point-marker)))))))

(defun ejira--find-child-heading-property (name value)
  "Get marker to child heading with property NAME with value VALUE."
  (ejira--find-child-heading-predicate
   (lambda () (equal (org-entry-get (point-marker) name) value))))

(defun ejira--find-child-heading (name)
  "Get marker to child heading with title NAME or nil."
  (ejira--find-child-heading-predicate
   (lambda () (equal (org-get-heading t t t t) name))))

(defun ejira--get-subheading (heading name)
  "Get marker to subheading NAME of HEADING, creating it if it does not exist."
  (org-with-point-at heading
    (or (ejira--find-child-heading name)
        (org-with-wide-buffer
         (ejira--with-expand-all
           (org-insert-heading-respect-content t)
           (insert name)
           (org-demote-subtree)
           (beginning-of-line)
           (point-marker))))))

(defun ejira--set-heading-summary (heading summary)
  "Set the heading text of HEADING to SUMMARY."
  (org-with-point-at heading
    (org-narrow-to-subtree)
    (goto-char (point-min))
    (org-with-wide-buffer
     (org-narrow-to-subtree)
     (when (search-forward
            (org-get-heading t t t t))
       (replace-match
        (s-replace "\\" "" (replace-regexp-in-string "\\\\\\(.\\)" "\\1"
                                                     summary)))))))

(defun ejira--set-summary (id summary)
  "Set the heading of item ID into SUMMARY."
  (ejira--set-heading-summary (ejira--find-heading id) summary))

(defun ejira--alist-get (l &rest keys)
  "Find a value from fields L recursively with KEYS."
  (let ((value (let* (key exists)
                 (while (and keys (listp l))
                   (setq key (car keys))
                   (setq exists nil)
                   (mapc (lambda (item)
                           (when (equal key (car item))
                             (setq exists t)))
                         (if (and (listp l)
                                  (listp (car l)))
                             l
                           nil))
                   (setq keys (cdr keys))
                   (if exists
                       (setq l (cdr (assoc key l)))
                     (setq l (or (cdr (assoc key l)) l))))
                 (when exists
                   l))))
    (if (stringp value)
        (decode-coding-string value 'utf-8)
      value)))

;;;###autoload
(defun ejira-get-id-under-point (&optional type exclude-comment)
  "Get ID and TYPE of the ticket under point.
With TYPE search up until an item of the given type is found.
With EXCLUDE-COMMENT do not include comments in the search."
  (interactive)
  (save-excursion
    (catch 'id-tag
      (while t
        (save-restriction
          (ejira--with-expand-all
            (org-narrow-to-subtree)
            (goto-char (point-min))

            (let ((found-id (or (org-entry-get (point-marker) "ID")
                                (unless exclude-comment
                                  (org-entry-get (point-marker) "CommId"))))
                  (found-type (org-entry-get (point-marker) "TYPE")))

              (when (and found-id (if type
                                      (equal found-type type)
                                    (s-starts-with-p "ejira-" found-type)))
                (when (equal found-type "ejira-comment")
                  (setq found-id (cons (org-entry-get (point-marker) "ID" t)
                                       found-id)))
                (throw 'id-tag (list found-type found-id (point-marker)))))))
        (org-up-element)))))

(defun ejira-issue-id-under-point ()
  "Get ID of the issue or project under point (ingores comments)."
  (nth 1 (ejira-get-id-under-point nil t)))

(defun ejira--delete-comment (key id)
  "Stage comment ID of item KEY for deletion via ejira-confirm on next save."
  (when-let ((m (ejira--find-child-heading-property "CommId" id)))
    (org-with-point-at m
      (org-set-property "PendingDelete" "t")))
  (message "ejira: comment deletion staged — save buffer to confirm."))

(defun ejira--progress-item (key)
  "Stage a Jira status transition for KEY via ejira-confirm on next save."
  (let* ((actions (jiralib2-get-actions key))
         (selected (rassoc (completing-read "Action: " (mapcar 'cdr actions))
                           actions)))
    (when selected
      (ejira--with-point-on key
        (org-set-property "PendingTransition" (cdr selected)))
      (message "ejira: transition '%s' staged — save buffer to confirm."
               (cdr selected)))))

(defun ejira--assign-issue (key &optional to-me)
  "Assign issue KEY locally. With TO-ME set to t assign it to me.
The actual Jira write happens via ejira-push on next save."
  (let* ((jira-users (ejira--get-assignable-users key))
         (fullname (if to-me
                       (cdr (assoc jiralib2-user-login-name jira-users))
                     (completing-read "Assignee: " (mapcar 'cdr jira-users))))
         (username (car (rassoc fullname jira-users))))
    (ejira--with-point-on key
      (org-set-property "Assignee" (if username fullname "")))

    ;; If assigned to me, add tag.
    (when ejira-assigned-tagname
      (if (equal fullname (ejira--my-fullname))
          (org-toggle-tag ejira-assigned-tagname 'on)
        (org-toggle-tag ejira-assigned-tagname 'off)))))

(defun ejira--get-fields-to-sync (&optional shallow)
  "Get a list of the fields that Ejira wants to sync.
With SHALLOW update only todo state."
  (if shallow
      `("key" "status" "assignee" "resolution")
    `("key" "priority" "assignee" "issuetype" "project" "summary" "description"
      "reporter" "duedate" "created" "updated" "status" "resolution" "parent" "timetracking"
      "comment" ,(symbol-name ejira-epic-field) ,(symbol-name ejira-sprint-field))))

(defvar ejira--my-fullname nil)
(defun ejira--my-fullname ()
  "Fetch full name of the currently logged in user."
  (or ejira--my-fullname
      (setq ejira--my-fullname
            (cdr (assoc 'displayName (jiralib2-get-user-info))))))

(defvar ejira--user-cache nil)
(defun ejira--get-users ()
  "Fetch user list from server and cache it for the session."
  (or ejira--user-cache
      (setq ejira--user-cache
            (append
             '(("Unassigned" . ""))
             (remove nil
                     (mapcar (lambda (user)
                               (let ((name (decode-coding-string
                                            (cdr (assoc 'displayName user)) 'utf-8))
                                     (key (cdr (assoc 'key user))))
                                 (unless (s-starts-with? "#" key)
                                   (cons key name))))
                             (jiralib2-get-users (car ejira-projects))))))))

;; A new link-type needs to be added, otherwise the ~-character at the beginning
;; of the link fools org to think this is a file path.
(org-link-set-parameters "jirauser" :follow nil :export nil)
(defun ejira-mention-user ()
  "Insert a username link."
  (interactive)
  (let* ((jira-users (ejira--get-users))
         (fullname (completing-read "User: " (mapcar 'cdr jira-users)))
         (username (car (rassoc fullname jira-users))))
    (insert (format "[[jirauser:~%s]]" username))))

(defun ejira--get-assignable-users (issue-key)
  "Fetch users that issue ISSUE-KEY can be assigned to."
  (append
   '((nil . "Unassigned"))
   (remove nil
           (mapcar (lambda (user)
                     (let ((name (decode-coding-string
                                  (cdr (assoc 'displayName user)) 'utf-8))
                           (key (cdr (assoc 'name user))))
                       (unless (s-starts-with? "#" key)
                         (cons key name))))
                   (jiralib2-get-assignable-users issue-key)))))

(defun ejira--set-epic (item epic)
  "Stage epic change for ITEM to EPIC via ejira-confirm on next save."
  (ejira--with-point-on item
    (org-set-property "PendingEpic" (or epic "")))
  (message "ejira: epic change staged — save buffer to confirm."))

(defun ejira--select-id-or-nil (prompt candidates)
  "Select a candidate from CANDIDATES or nil. Display PROMPT."
  (let ((choice (completing-read
                 prompt
                 (mapcar (-partial #'nth 0)
                         (cons '("*nil*", "" ()) candidates)))))
    (unless (equal choice "*nil*")
      choice)))

(defun ejira--select-project ()
  "Select a project interactively."
  (completing-read
   "Select project: "
   (mapcar (-partial #'nth 0)
           (ejira--get-headings-in-agenda-files :type "ejira-project"))))

(defun ejira--select-story ()
  "Select a story interactively."
  (completing-read
   "Select story: "
   (mapcar (-partial #'nth 0)
           (ejira--get-headings-in-agenda-files :type "ejira-story"))))

(defun ejira--get-headings-in-file (filename plist)
  "Get ejira headings from FILENAME with parameters PLIST.
Parameters:
  :type     match for the TYPE-property (defaults to task, project and epic)
  :resolved match for the resolved status of the item. either 'todo or 'done
  :tags     match for the tags (defaults to any)
Without type, match for all ejira types (task, epic, story, subtask)"
  (let* ((type-arg (or (plist-get plist :type) '("ejira-issue" "ejira-epic"
                                                 "ejira-story" "ejira-subtask")))
         (types (if (listp type-arg) type-arg `(,type-arg)))
         (resolved (plist-get plist :todo))
         (tags (plist-get plist :tags)))
    (with-current-buffer (pcase filename
                           ((pred bufferp) filename)
                           ((pred stringp) (find-file-noselect filename t)))
      (org-with-wide-buffer
       (ejira--with-expand-all
         (goto-char (point-min))
         (cl-loop while (search-forward-regexp "^\\*\\{1,4\\} " nil t)
                  if (and (when-let ((type (org-entry-get (point) "TYPE")))
                            (member type types))
                          (if tags
                              (let ((tags_ (org-get-tags)))
                                (equal tags (-intersection tags tags_)))
                            t)
                          (if resolved
                              (equal resolved (if (org-entry-is-done-p) "done" "todo"))
                            t))
                  collect `(,(org-entry-get (point) "ID")
                            ,(ejira--strip-properties (org-get-heading t t t t))
                            ,(org-get-tags)
                            ,(org-entry-get (point) "TYPE"))))))))

(defun ejira--get-headings-in-agenda-files (&rest plist)
  "Get ejira headings from org agenda files, with parameters PLIST."
  (-mapcat (-rpartial #'ejira--get-headings-in-file plist) (org-agenda-files)))

(defun ejira--get-headings-in-current-file (&rest plist)
  "Get ejira headings from the current file, with parameters PLIST."
  (ejira--get-headings-in-file plist (buffer-file-name)))

(defun ejira--date-to-time (date)
  "Return DATE in internal format, if it is not nil."
  (when date
    (date-to-time date)))

(defun ejira--select-issuetype ()
  "Select a type name from types available in the server."
  (nth 0 (split-string
          (completing-read
           "Issue type: "
           (mapcar (lambda (m)
                     (format "%-15s\t%s"
                             (alist-get 'name m)
                             (alist-get 'description m)))
                   (jiralib2-get-issuetypes))) "\t" t "\s*")))

(defun ejira--get-clocked-issue ()
  "Get key of the currently clocked issue."
  (unless (marker-buffer org-clock-marker)
    (user-error "Not clocked in to an issue"))
  (org-with-point-at org-clock-marker
    (ejira-issue-id-under-point)))

(defun ejira-get-sprint-name (data)
  "Parse sprint name from DATA. Return NIL if not found."
  (let ((name (last (mapcar #'ejira-sprint-name
                            (mapcar #'ejira--parse-sprint data)))))
    (when (car name)
      ;; Spaces are not valid in a tagname.
      (ejira--to-tagname (car name)))))

(defun ejira--to-tagname (str)
  "Convert STR into a valid org tag."
  (concat ejira-sprint-tagname-prefix
          (replace-regexp-in-string "[^a-zA-Z0-9_]+" "_" str)))


(provide 'ejira-core)
;;; ejira-core.el ends here
